#!/bin/sh
if [ $# != 0 ]; then
	echo 'displaying: Prints the $DISPLAY of the current user.' > /dev/stderr
	[ "$1" = -h ] || [ "$1" = --help ]; exit
fi
console="$(cat /sys/class/tty/tty0/active)"
w --no-header | sed -nE "s/[^ ]+ *//; s/^$console .* (:[0-9]+).*/\1/; /^:/ { p; q }"
