#!/bin/sh

if ! command -v arecord > /dev/null; then
	echo 'numen requires the alsa-utils package.' >&2
	exit 1
fi

handler=kernel audio= mic= speechless=
args="$(getopt -n numen -o h -l audio:,help,gadget,kernel,list-mics,mic:,speechless,version,x11 -- "$@")" || exit
eval set -- "$args"
while :; do
	case "$1" in
	--audio) audio="$2"; shift 2;;
	-h|--help) echo "numen [PHRASE_FILE...]

--audio=FILE Specify an audio file to use instead of the microphone.
--gadget     Use the gadget handler to perform the actions over USB.
--kernel     Use the kernel handler to perform the actions (the default).
--list-mics  List audio devices and exit.
--mic=NAME   Select the audio device.
--speechless Don't do speech recognition (to just send actions with numenc).
--version    Print the version and exit.
--x11        Use the X11 handler to perform the actions."; exit;;
	--kernel) handler=kernel; shift;;
	--gadget) handler=gadget; shift;;
	--list-mics) arecord -L | sed -E '/^sysdefault:/ !d; s/.*=//; N'; exit;;
	--mic) mic="$2"; shift 2;;
	--speechless) speechless=1; shift;;
	--version) printf %s\\n "$NUMEN_VERSION"; exit;;
	--x11) handler=x11; shift;;
	--) shift; break;;
	esac
done

if [ $# = 0 ]; then
	if [ -d "${XDG_CONFIG_HOME:-$HOME/.config}"/numen/phrases ]; then
		set -- "${XDG_CONFIG_HOME:-$HOME/.config}/numen/phrases/"*.phrases
	else
		set -- /etc/numen/phrases/*.phrases
	fi
fi

mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/numen/mods"
pipe="${NUMEN_PIPE:-/tmp/numen_pipe}"
model="${NUMEN_MODEL:-model}"

if [ -p "$pipe" ] && /bin/echo 1<>"$pipe" >"$pipe"; then
	echo "numen: another instance is already reading the pipe: $pipe" >&2
	exit 1
fi
rm -f -- "$pipe" || exit 1
trap 'rm -f -- "$pipe"; pkill -P $$; trap - EXIT; exit' EXIT INT TERM HUP
mkfifo -m 600 "$pipe" || exit 1

export NUMEN_HANDLER="$handler"
export NUMEN_PIPE="$pipe"
export NUMEN_SHELL="${NUMEN_SHELL:-/bin/sh}"

libexec=/usr/libexec/numen
if ! [ "$speechless" ]; then
	if [ "$audio" ]; then
		"$libexec/speech" "$model" "$@" < "$audio" | "$libexec/scribe" > "$pipe" &
	else
		"$libexec/record" "$mic" | "$libexec/speech" "$model" "$@" | "$libexec/scribe" > "$pipe" &
	fi
fi

"$libexec/instructor" < "$pipe" | "$libexec/handlers/$handler" &
wait $!
