#!/bin/sh
# record [MICROPHONE]
# Outputs microphone audio formatted well for the language model.
mic=default
if [ "$1" ]; then
	mic="$1"; shift
	[ "$mic" = "${mic#*CARD=}" ] && mic="sysdefault:CARD=$mic"
elif arecord -L | grep -qx sysdefault:CARD=Microphone; then
	mic=sysdefault:CARD=Microphone
fi
arecord -D "$mic" --nonblock --quiet -f S16_LE -c 1 -r 16000
