#!/bin/sh
# record [MICROPHONE]
# Outputs microphone audio formatted well for the language model.

mic=default
if [ "$1" ]; then
	mic="$1"; shift
	[ "$mic" = "${mic#*CARD=}" ] && mic="sysdefault:CARD=$mic"
elif arecord -L | grep -qx sysdefault:CARD=Microphone; then
	mic=sysdefault:CARD=Microphone
fi

if [ "$NUMEN_VERBOSE" ]; then
	printf %s\\n "Microphone: $mic" >&2
fi

t="$(date +%s)"
arecord -q -D "$mic" -f S16_LE -c 1 -r 16000
[ "$(($(date +%s) - t))" -lt 2 ] && exit 1
while :; do
	arecord -q -D "$mic" -f S16_LE -c 1 -r 16000 | tail -c +45
	sleep 1
done
