#!/usr/libexec/numen/awk -f
# Filters the output of ./speech for ./instructor and continuously writes transcript results to a file.
function erase(file) { system("> "file) }
BEGIN {
	f = ENVIRON["HOME"]"/.local/share/numen/transcripts"
	if (length(ENVIRON["XDG_DATA_HOME"])) f = ENVIRON["XDG_DATA_HOME"]"/numen/transcripts"
}
/^transcript1[^0-9]/ { erase(f); close(f); print "set NUMEN_TRANSCRIPT echo \""substr($0, 13)"\""; fflush() }
/^transcript/ { sub(/^[^:]*:/, ""); print > f; fflush(f); next }  # Note > appends after the first time until close
{ print; fflush() }
