#!/bin/sh
export NUMEN_HANDLER=x11

alias print='printf %s\\n'
alias shell='${NUMEN_SHELL:-/bin/sh}'

# Returns whether $1 starts with $2.
prefixed() { [ "${1#$2}" != "$1" ]; }

iscapson() {
	command -v xset > /dev/null || return 1
	xset q | awk '/Caps Lock/ {exit $4 == "off"}'
}
iscapsoff() {
	command -v xset > /dev/null || return 1
	xset q | awk '/Caps Lock/ {exit $4 != "off"}'
}

export NUMEN_KEY_DELAY="${NUMEN_KEY_DELAY:-10}"
export NUMEN_TYPE_DELAY="${NUMEN_TYPE_DELAY:-10}"
if [ "$NUMEN_KEY_HOLD" ]; then
	echo 'numen: currently the X11 handler ignores $NUMEN_KEY_HOLD' >&2
fi
if [ "$NUMEN_TYPE_HOLD" ]; then
	echo 'numen: currently the X11 handler ignores $NUMEN_TYPE_HOLD' >&2
fi
myxdotool() {
	while IFS= read -r line; do
		if prefixed "$line" type; then
			# The '' stops xdotool complaining if there's nothing to type.
			xdotool $(print ${line%%-- *}) -- "${line#*-- }" ''
		else
			xdotool $line
		fi
	done
}

if ! command -v xdotool >/dev/null; then
	echo 'numen: the x11 handler requires the xdotool command' >&2
	exit 1
elif ! command -v xset >/dev/null; then
	echo 'numen: the x11 handler requires the xset command' >&2
	exit 1
fi

while IFS= read -r line; do
	line="${line#local}"
	if prefixed "$line" key; then
		print "${line%% *} --delay $NUMEN_KEY_DELAY -- ${line#* }"
	elif prefixed "$line" type; then
		export NUMEN_TEXT="${line#type }"
		print "type --delay $((NUMEN_TYPE_DELAY*2)) -- $NUMEN_TEXT"
	elif [ "$line" = capson ]; then
		iscapsoff && print "key --delay $NUMEN_KEY_DELAY Caps_Lock"
	elif [ "$line" = capsoff ]; then
		iscapson && print "key --delay $NUMEN_KEY_DELAY Caps_Lock"
	elif prefixed "$line" click; then
		print "$line" | sed 's/left/1/; s/middle/2/; s/right/3/'
	elif [ "$line" = scrollup ]; then
		print 'click 4'
	elif [ "$line" = scrolldown ]; then
		print 'click 5'
	elif prefixed "$line" mousemove; then
		print "mousemove_relative --${line#mousemove}"
	elif prefixed "$line" mouseto; then
		coord="${line#* }"
		size="$(xdotool search --maxdepth 0 --name '' getwindowgeometry)"
		size="${size##* }"
		awk -v w="${size%x*}" -v h="${size#*x}" -v x="${coord% *}" -v y="${coord#* }" 'BEGIN {print "mousemove -- "w*x" "h*y}'
	elif prefixed "$line" pen; then
		export NUMEN_TEXT="$(shell -c "${line#pen }")"
		print "$NUMEN_TEXT" | sed "s/^/type --delay $((NUMEN_TYPE_DELAY*2)) -- /; 1 !s/^/key --delay $((NUMEN_TYPE_DELAY*2)) -- Return\n/"
	elif prefixed "$line" eval; then
		shell -c "${line#eval }" > "$NUMEN_PIPE"
	elif prefixed "$line" set; then
		line="${line#set }"
		export -- "${line%% *}=$(shell -c "${line#* }")"
	elif prefixed "$line" handler; then
		exec "/usr/libexec/numen/handlers/${line#handler }"
	fi
done | myxdotool
